openapi: "3.1.0"
info:
  title: "clientes API"
  description: "clientes API"
  version: "1.0.0"
servers:
  - url: "https://clientes"
paths:
  /clientes/{id}:
    put:
      summary: "PUT clientes/{id}"
      operationId: "updateCliente"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Cliente"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Cliente"
    delete:
      summary: "DELETE clientes/{id}"
      operationId: "deleteCliente"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Void"
    get:
      summary: "GET clientes/{id}"
      operationId: "getClienteById"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Cliente"
  /clientes:
    post:
      summary: "POST clientes"
      operationId: "createCliente"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Cliente"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Cliente"
    get:
      summary: "GET clientes"
      operationId: "getAllClientes"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Cliente"
components:
  schemas:
    Persona:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
        nombre:
          type: "string"
        genero:
          type: "string"
        edad:
          type: "integer"
          format: "int32"
        identificacion:
          type: "string"
        direccion:
          type: "string"
        telefono:
          type: "string"
    Cliente:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
        persona:
          $ref: "#/components/schemas/Persona"
        email:
          type: "string"
        contrasena:
          type: "string"
        estado:
          type: "string"
    Void:
      type: "object"
      properties: { }